# Generated by Django 5.0 on 2024-02-20 08:38

import django.db.models.deletion
import gymapp.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_trainer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(default='san', max_length=100)),
                ('image', models.ImageField(default='product.jpg', upload_to=gymapp.models.user_directory_path)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
