# Generated by Django 5.0 on 2024-02-20 10:51

import gymapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default='product.mp4', upload_to=gymapp.models.user_directory_path),
        ),
    ]
