# Generated by Django 5.0 on 2024-03-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_remove_productimage_product_workout_workoutimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='expertise',
            new_name='password',
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
