# Generated by Django 5.0 on 2024-03-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_rename_expertise_trainer_password_trainer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='username',
        ),
    ]
