# Generated by Django 5.0 on 2024-04-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
    ]
