# Generated by Django 5.0 on 2024-03-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_rename_name_trainer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutimage',
            name='product',
        ),
        migrations.AddField(
            model_name='workoutimage',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gymapp.workout'),
        ),
        migrations.AlterField(
            model_name='workoutimage',
            name='image',
            field=models.ImageField(blank=True, default='workout.jpg', null=True, upload_to='workout-images'),
        ),
    ]
