# Generated by Django 5.0 on 2024-03-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_remove_workoutimage_product_workoutimage_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutimage',
            name='workout',
        ),
        migrations.AddField(
            model_name='workoutimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.workout'),
        ),
        migrations.AlterField(
            model_name='workoutimage',
            name='image',
            field=models.ImageField(default='workout.jpg', upload_to='workout-images'),
        ),
    ]
