# Generated by Django 5.0 on 2024-03-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_remove_workoutimage_workout_workoutimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutimage',
            name='product',
        ),
        migrations.AddField(
            model_name='workoutimage',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gymapp.workout'),
        ),
    ]
