# Generated by Django 5.0 on 2024-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_remove_workoutimage_workout_workoutimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
