# Generated by Django 5.0 on 2024-03-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_alter_workout_description_alter_workout_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutimage',
            old_name='product',
            new_name='workout',
        ),
    ]
