# Generated by Django 5.0 on 2024-03-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_rename_workout_workoutimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutimage',
            name='product',
        ),
        migrations.AddField(
            model_name='workoutimage',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymapp.workout'),
        ),
    ]
