# Generated by Django 5.0 on 2024-03-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_remove_workoutimage_product_workoutimage_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutimage',
            old_name='workout',
            new_name='product',
        ),
    ]
