# Generated by Django 5.0 on 2024-03-02 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0017_rename_workout_workoutimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.workout'),
        ),
    ]
