# Generated by Django 5.0 on 2024-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_calorieintake_delete_calorietracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
