# Generated by Django 5.0 on 2024-03-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_alter_workoutimage_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutImage',
        ),
    ]
