# Generated by Django 5.0 on 2024-03-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0019_delete_workoutimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, default='No description available', null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(default='san', max_length=100),
        ),
        migrations.CreateModel(
            name='WorkoutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='workout.jpg', upload_to='workout-images')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymapp.workout')),
            ],
            options={
                'verbose_name_plural': 'Workout Images',
            },
        ),
    ]
