# Generated by Django 5.0 on 2024-03-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0020_alter_workout_description_alter_workout_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTrainerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('certification', models.ImageField(upload_to='certifications/')),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
    ]
