# Generated by Django 5.0 on 2024-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0023_workout_watch_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
