# Generated by Django 5.0 on 2024-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0025_remove_transaction_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
