# Generated by Django 5.0 on 2024-05-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0028_remove_transaction_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='months',
            field=models.IntegerField(default=1),
        ),
    ]
